import { describe, expect, test } from "bun:test"
import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"

function readUtf8(relativePath: string): string {
  return readFileSync(join(import.meta.dir, relativePath), "utf8")
}

describe("OpenCodex renderer shell contract", () => {
  test("renderer stops requesting cloud-auth desktop identity", () => {
    const appSource = readUtf8("App.tsx")
    const layoutSource = readUtf8("features/layout/agents-layout.tsx")
    const profileTabSource = readUtf8("components/dialogs/settings-tabs/agents-profile-tab.tsx")
    const modelsTabSource = readUtf8("components/dialogs/settings-tabs/agents-models-tab.tsx")
    const mcpTabSource = readUtf8("components/dialogs/settings-tabs/agents-mcp-tab.tsx")
    const mcpIndicatorSource = readUtf8("features/agents/ui/mcp-servers-indicator.tsx")
    const activeChatSource = readUtf8("features/agents/main/active-chat.tsx")
    const acpTransportSource = readUtf8("features/agents/lib/acp-chat-transport.ts")
    const ipcTransportSource = readUtf8("features/agents/lib/ipc-chat-transport.ts")
    const backendEditorSource = readUtf8("features/onboarding/opencodex-backend-editor.tsx")
    const billingPageSource = readUtf8("features/onboarding/billing-method-page.tsx")
    const onboardingIndexSource = readUtf8("features/onboarding/index.ts")
    const sidebarSource = readUtf8("features/sidebar/agents-sidebar.tsx")
    const agentsContentSource = readUtf8("features/agents/ui/agents-content.tsx")
    const betaTabSource = readUtf8("components/dialogs/settings-tabs/agents-beta-tab.tsx")
    const backendControlSource = readUtf8("features/opencodex/backend-control-view.tsx")
    const rendererAtomsSource = readUtf8("lib/atoms/index.ts")
    const agentsAtomsSource = readUtf8("features/agents/atoms/index.ts")
    const loginPageSource = readUtf8("login.html")
    const codexLoginHookPath = join(
      import.meta.dir,
      "features/agents/hooks/use-codex-login-flow.ts",
    )
    const codexLoginContentPath = join(
      import.meta.dir,
      "features/agents/components/codex-login-content.tsx",
    )

    expect(appSource).not.toContain("window.desktopApi?.getUser")
    expect(layoutSource).not.toContain("window.desktopApi.getUser()")
    expect(layoutSource).not.toContain("window.desktopApi?.logout")
    expect(layoutSource).not.toContain("ClaudeLoginModal")
    expect(layoutSource).not.toContain("CodexLoginModal")
    expect(layoutSource).not.toContain("claudeLoginModalConfigAtom")
    expect(profileTabSource).not.toContain("window.desktopApi?.getUser")
    expect(profileTabSource).not.toContain("window.desktopApi?.updateUser")
    expect(modelsTabSource).not.toContain("trpc.codex.")
    expect(modelsTabSource).not.toContain("trpc.claudeCode")
    expect(modelsTabSource).not.toContain("trpc.anthropicAccounts")
    expect(mcpTabSource).not.toContain("trpc.claude.")
    expect(mcpTabSource).not.toContain("trpc.codex.")
    expect(mcpIndicatorSource).not.toContain("trpc.claude.")
    expect(mcpIndicatorSource).not.toContain("trpc.codex.")
    expect(activeChatSource).not.toContain("trpcClient.claude.respondToolApproval")
    expect(activeChatSource).not.toContain("new ACPChatTransport")
    expect(activeChatSource).not.toContain("new IPCChatTransport")
    expect(acpTransportSource).not.toContain("trpcClient.codex.")
    expect(ipcTransportSource).not.toContain("trpcClient.claude.")
    expect(mcpTabSource).toContain("trpc.opencodex.getAllMcpConfig")
    expect(mcpIndicatorSource).toContain("trpc.opencodex.getMcpConfig")
    expect(activeChatSource).toContain("trpcClient.opencodex.respondToolApproval")
    expect(activeChatSource).toContain("createOpenCodexChatTransport")
    expect(acpTransportSource).toContain("trpcClient.opencodex.")
    expect(ipcTransportSource).toContain("trpcClient.opencodex.")
    expect(modelsTabSource).toContain("trpc.opencodex.getBackendSurface")
    expect(modelsTabSource).toContain("OpenCodexBackendEditor")
    expect(billingPageSource).toContain("OpenCodexBackendEditor")
    expect(backendEditorSource).toContain("window.desktopApi.getBackendHostState()")
    expect(backendEditorSource).toContain("window.desktopApi.saveOpenCodexBackendConfig")
    expect(backendEditorSource).toContain("Save Backend")
    expect(onboardingIndexSource).not.toContain("AnthropicOnboardingPage")
    expect(onboardingIndexSource).not.toContain("ApiKeyOnboardingPage")
    expect(onboardingIndexSource).not.toContain("CodexOnboardingPage")
    expect(sidebarSource).not.toContain("Log out")
    expect(sidebarSource).not.toContain("AuthDialog")
    expect(sidebarSource).not.toContain("Login")
    expect(sidebarSource).not.toContain("remoteTrpc.automations")
    expect(sidebarSource).not.toContain("getOpenCodexAutomationsUrl")
    expect(sidebarSource).not.toContain("<InboxButton />")
    expect(sidebarSource).not.toContain("<AutomationsButton />")
    expect(sidebarSource).toContain("OpenCodex Backend")
    expect(agentsContentSource).not.toContain("AutomationsView")
    expect(agentsContentSource).not.toContain("AutomationsDetailView")
    expect(agentsContentSource).not.toContain("InboxView")
    expect(agentsContentSource).not.toContain("betaAutomationsEnabledAtom")
    expect(agentsContentSource).not.toContain("remoteTrpc.automations")
    expect(agentsContentSource).toContain("BackendControlView")
    expect(betaTabSource).not.toContain("remoteTrpc.agents.getAgentsSubscription")
    expect(betaTabSource).not.toContain("Automations & Inbox")
    expect(betaTabSource).toContain("Backend Control Center")
    expect(rendererAtomsSource).not.toContain("betaAutomationsEnabledAtom")
    expect(rendererAtomsSource).not.toContain("automationDetailIdAtom")
    expect(rendererAtomsSource).not.toContain("automationTemplateParamsAtom")
    expect(rendererAtomsSource).not.toContain("inboxSelectedChatIdAtom")
    expect(rendererAtomsSource).not.toContain("agentsInboxSidebarWidthAtom")
    expect(rendererAtomsSource).not.toContain("inboxMobileViewModeAtom")
    expect(agentsAtomsSource).not.toContain("\"automations\"")
    expect(agentsAtomsSource).not.toContain("\"automations-detail\"")
    expect(agentsAtomsSource).not.toContain("\"inbox\"")
    expect(agentsAtomsSource).toContain("\"backend-control\"")
    expect(backendControlSource).toContain("trpc.opencodex.getBackendSurface")
    expect(backendControlSource).toContain("trpc.opencodex.getAllMcpConfig")
    expect(backendControlSource).toContain("trpc.external.openInFinder")
    expect(backendControlSource).toContain("OpenCodexBackendEditor")
    expect(loginPageSource).not.toContain("onAuthSuccess")
    expect(loginPageSource).not.toContain("startAuthFlow")
    expect(loginPageSource).not.toContain("Sign in")
    expect(existsSync(codexLoginHookPath)).toBe(false)
    expect(existsSync(codexLoginContentPath)).toBe(false)

    expect(profileTabSource).toContain("window.desktopApi.getLocalProfile()")
    expect(profileTabSource).toContain("window.desktopApi.updateLocalProfile({ displayName: trimmed })")
    expect(layoutSource).toContain("window.desktopApi?.resetLocalWorkspace")
    expect(sidebarSource).toContain("Reset local workspace")
    expect(loginPageSource).toContain("OpenCodex local backend")
  })
})
